version: 2

jobs:
        build:
                machine: true
                steps:
                        - checkout
                        - run: cd ~ ; wget -qO- get.nextflow.io | bash ; chmod 755 nextflow ; sudo ln -s ~/nextflow /usr/local/bin/ ; sudo apt-get install graphviz
                        - run: cd ~ && git clone https://github.com/iarcbioinfo/data_test.git
                        - run: echo " docker.runOptions = '-u $(id -u):$(id -g)' " > ~/.nextflow/config
                        - run: cd ~/project/ ; docker build -t nalcala/mutect-nf .
                        - run: cd ~/project/ ; docker build -t nalcala/mutect-nf_gatk3 -f Dockerfile_gatk3 .
                        - run: cd ~/project/ ; docker build -t nalcala/mutect-nf_gatk2 -f Dockerfile_gatk2 .
                        - run: cd ; nextflow run ~/project/mutect.nf --help
                        - run: cd ; wget https://github.com/broadinstitute/mutect/releases/download/1.1.5/muTect-1.1.5-bin.zip; unzip muTect-1.1.5-bin.zip && docker run -v ${PWD}:/test nalcala/mutect-nf_gatk2 java -jar test/muTect-1.1.5.jar --help
                        - run: cd ; docker run nalcala/mutect-nf_gatk3 java -jar /mutect-nf_gatk3/bin/GenomeAnalysisTK.jar --help
                        - run: cd ; nextflow run ~/project/mutect.nf -with-docker nalcala/mutect-nf --tumor_bam_folder ~/data_test/BAM/test/ --normal_bam_folder ~/data_test/BAM/test/ --bed ~/data_test/BED/TP53_exon2_11.bed --ref ~/data_test/REF/17.fasta --nsplit 2 -with-dag dag.html
                        - run: cd ; nextflow run ~/project/mutect.nf -with-docker nalcala/mutect-nf_gatk3 --tumor_bam_folder ~/data_test/BAM/test/ --normal_bam_folder ~/data_test/BAM/test/ --bed ~/data_test/BED/TP53_exon2_11.bed --ref ~/data_test/REF/17.fasta --mutect2_jar ~/GenomeAnalysisTK.jar --nsplit 2 --out_folder mutect2_results
                        - run: cd ; nextflow run ~/project/mutect.nf -with-docker nalcala/mutect-nf_gatk2 --tumor_bam_folder ~/data_test/BAM/test/ --normal_bam_folder ~/data_test/BAM/test/ --bed ~/data_test/BED/TP53_exon2_11.bed --ref ~/data_test/REF/17.fasta --mutect_jar ~/muTect-1.1.5.jar --nsplit 2
                        - run: cd ; cp ~/dag* ~/project/.
                        - deploy:
                                branch: [master, dev]
                                command: chmod +x deploy.sh && ./deploy.sh
